# Generated by Django 5.2.14 on 2026-05-11 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuartel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cuartel', models.CharField(max_length=100)),
                ('tipo_cultivo', models.CharField(blank=True, max_length=100, null=True)),
                ('variedad', models.CharField(blank=True, max_length=100, null=True)),
                ('forma_riego', models.CharField(blank=True, choices=[('goteo', 'Goteo'), ('aspersion', 'Aspersión'), ('microaspersion', 'Microaspersión'), ('surcos', 'Surcos'), ('tendido', 'Tendido'), ('otro', 'Otro')], max_length=50, null=True)),
                ('anio_plantacion', models.IntegerField(blank=True, null=True)),
                ('superficie', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cuartel',
                'verbose_name_plural': 'Cuarteles',
                'db_table': 'cuarteles',
                'ordering': ['-created_at', '-id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Predio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_predio', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(blank=True, max_length=150, null=True)),
                ('superficie', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.BooleanField(blank=True, default=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Predio',
                'verbose_name_plural': 'Predios',
                'db_table': 'predios',
                'ordering': ['-created_at', '-id'],
                'managed': False,
            },
        ),
    ]
