# Generated by Django 5.2.14 on 2026-05-14 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_cuartel_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cosecha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cosecha', models.DateField()),
                ('tipo_cosecha', models.CharField(blank=True, max_length=100, null=True)),
                ('cantidad_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cantidad_bins', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('calidad', models.CharField(blank=True, choices=[('excelente', 'Excelente'), ('muy_buena', 'Muy buena'), ('buena', 'Buena'), ('regular', 'Regular'), ('mala', 'Mala')], max_length=50, null=True)),
                ('destino', models.CharField(blank=True, choices=[('mercado', 'Mercado'), ('venta_directa', 'Venta directa'), ('procesamiento', 'Procesamiento'), ('almacenamiento', 'Almacenamiento'), ('otro', 'Otro')], max_length=100, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('planificada', 'Planificada'), ('en_proceso', 'En proceso'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='completada', max_length=50)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Cosecha',
                'verbose_name_plural': 'Cosechas',
                'db_table': 'cosechas',
                'ordering': ['-fecha_cosecha', '-created_at', '-id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fertilizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_aplicacion', models.DateField()),
                ('producto', models.CharField(blank=True, max_length=150, null=True)),
                ('dosis', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unidad', models.CharField(blank=True, max_length=50, null=True)),
                ('metodo_aplicacion', models.CharField(blank=True, max_length=100, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Fertilización',
                'verbose_name_plural': 'Fertilizaciones',
                'db_table': 'fertilizacion',
                'ordering': ['-fecha_aplicacion', '-created_at', '-id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Riego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_riego', models.DateField()),
                ('tipo_riego', models.CharField(blank=True, max_length=100, null=True)),
                ('horas_riego', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('caudal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Riego',
                'verbose_name_plural': 'Riegos',
                'db_table': 'riego',
                'ordering': ['-fecha_riego', '-created_at', '-id'],
                'managed': False,
            },
        ),
    ]
