# Generated by Django 5.2.14 on 2026-08-22 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_predios_riego_labores_agricolas'),
    ]

    operations = [
        migrations.CreateModel(
            name='AplicacionQuimica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_aplicacion', models.DateField()),
                ('producto', models.CharField(max_length=150)),
                ('tipo_producto', models.CharField(blank=True, max_length=100, null=True)),
                ('dosis', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unidad', models.CharField(blank=True, max_length=50, null=True)),
                ('metodo_aplicacion', models.CharField(blank=True, max_length=100, null=True)),
                ('responsable', models.CharField(blank=True, max_length=120, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estado', models.BooleanField(blank=True, default=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Aplicación química',
                'verbose_name_plural': 'Aplicaciones químicas',
                'db_table': 'aplicaciones_quimicas',
                'ordering': ['-fecha_aplicacion', '-created_at', '-id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LaborAgricola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo_labor', models.CharField(choices=[('poda', 'Poda'), ('brote', 'Brote'), ('limpieza', 'Limpieza'), ('mantencion', 'Mantención'), ('revision', 'Revisión'), ('otro', 'Otro')], max_length=50)),
                ('subtipo', models.CharField(blank=True, max_length=80, null=True)),
                ('responsable', models.CharField(blank=True, max_length=120, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Labor agrícola',
                'verbose_name_plural': 'Labores agrícolas',
                'db_table': 'labores_agricolas',
                'ordering': ['-fecha', '-created_at', '-id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LogActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('CREAR', 'Crear'), ('EDITAR', 'Editar'), ('ELIMINAR', 'Eliminar'), ('LOGIN', 'Iniciar sesión'), ('LOGOUT', 'Cerrar sesión'), ('CONSULTA', 'Consulta')], max_length=100)),
                ('modulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Log de actividad',
                'verbose_name_plural': 'Logs de actividad',
                'db_table': 'logs_actividad',
                'ordering': ['-fecha', '-id'],
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('tecnico', 'PRODESAL'), ('productor', 'Productor')], max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='sector',
            field=models.CharField(blank=True, choices=[('Zaino', 'Zaino'), ('Jahuelito', 'Jahuelito'), ('Santa Filomena', 'Santa Filomena'), ('El Llano', 'El Llano'), ('Tabolango', 'Tabolango'), ('Lo Galdames', 'Lo Galdames')], max_length=100),
        ),
        migrations.CreateModel(
            name='ComentarioTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(choices=[('predio', 'Predio'), ('cuartel', 'Cuartel'), ('riego', 'Riego'), ('fertilizacion', 'Fertilización'), ('cosecha', 'Cosecha'), ('aplicacion_quimica', 'Aplicación química'), ('labor_agricola', 'Labor agrícola')], max_length=30)),
                ('objeto_id', models.PositiveIntegerField()),
                ('comentario', models.TextField()),
                ('leido', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('productor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_recibidos', to='usuarios.usuario')),
                ('usuario_prodesal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_realizados', to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Comentario técnico',
                'verbose_name_plural': 'Comentarios técnicos',
                'db_table': 'comentarios_tecnicos',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('mensaje', models.TextField()),
                ('leido', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('productor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_recibidas', to='usuarios.usuario')),
                ('usuario_generador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_enviadas', to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'db_table': 'notificaciones',
                'ordering': ['-fecha', '-id'],
            },
        ),
    ]
