# Generated by Django 5.2.14 on 2026-08-22 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_aplicacionquimica_laboragricola_logactividad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='modulo',
            field=models.CharField(blank=True, choices=[('predio', 'Predio'), ('cuartel', 'Cuartel'), ('riego', 'Riego'), ('fertilizacion', 'Fertilización'), ('cosecha', 'Cosecha'), ('aplicacion_quimica', 'Aplicación química'), ('labor_agricola', 'Labor agrícola')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='objeto_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
