from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("usuarios", "0008_repair_logs_actividad_table"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                CREATE TABLE IF NOT EXISTS logs_actividad (
                    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    usuario_id bigint NOT NULL REFERENCES usuarios(id) ON DELETE NO ACTION,
                    accion varchar(100) NOT NULL,
                    modulo varchar(100) NOT NULL,
                    descripcion text NULL,
                    fecha timestamp with time zone NULL DEFAULT CURRENT_TIMESTAMP
                )
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
